#!/bin/bash
#
# Prints the current CPU frequency of all cores.
# Author: Artur O. Commander.Alchemy@gmail.com (Justice @ Freenode #Archlinux)

sudo awk '{print "CPU " core++ ":", ($1)/1000, "Mhz"}' /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq