#!/bin/bash

# Configuration
root="/srv/http"
app="MysStund"
dev_path="/home/commander/Projects"

# Font
bold="\e[1m"
red="\e[91m"
green="\e[92m"
blink="\e[5m"

# Reset all attributes
reset="\e[0m"



echo -e "$red$bold$blink[Updating Server]$reset"
echo -e "$red$bold[Removing old MysStund dir...]$reset"
sudo rm -r --preserve-root "$root"/"$app"

echo -e "$red$bold[Moving files from development dir...]$reset"
sudo cp -R "$dev_path"/"$app"/"$app" "$root"

echo -e "$red$bold[Updating permissions...]$reset"
sudo chown -R http:http "$root"/"$app"

echo -e "$red$bold[Restarting apache2...]$reset"
sudo systemctl restart httpd

echo -e "$green$bold[Complete!]$reset"

exit 0
