#!/bin/bash
#
# Shows system voltage and CPU frequency in a fancy fashion.
# Author: Artur O. Commander.Alchemy@gmail.com (Justice @ Freenode #Archlinux)

source ~/.bin/watcher
watcher 1 "sensors | egrep \"ALARM|$\" --color=always; sudo cpupower monitor -m Mperf | cut -d\| -f1,4"





